Fixup build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,20 +1,34 @@
 version: 2.0
 jobs:
-  gcc8-regress-cov:
+  "gcc8-debug-cov":
+    docker:
+      - image: ceeac/boomerang-build-env:gcc8-debug-cov
+    steps:
+      - run: |
+          cd ~/project && mkdir build && cd build &&
+          cmake -DCMAKE_BUILD_TYPE=Debug -DBOOMERANG_BUILD_UNIT_TESTS=ON -DBOOMERANG_BUILD_REGRESSION_TESTS=OFF -DBOOMERANG_ENABLE_COVERAGE=ON .. &&
+          make -j$(nproc) && make test
+      - run: |
+          lcov --directory . --capture --output-file coverage.info &&
+          lcov -r coverage.info '*.l' '/usr/*' '*/tests/unit-tests/*' --output-file coverage.info &&
+          lcov --list coverage.info"
+          echo "Uploading CodeCov reports" && bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X xcode -F unittests -s "$(pwd)" || echo \"CodeCov coverage report generation failed!\"
+
+  "gcc8-regress-cov":
     docker:
       - image: ceeac/boomerang-build-env:gcc8-regress-cov
     steps:
       - run: |
           cd ~/project && mkdir build && cd build &&
           cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBOOMERANG_BUILD_UNIT_TESTS=OFF -DBOOMERANG_BUILD_REGRESSION_TESTS=ON -DBOOMERANG_ENABLE_COVERAGE=ON .. &&
-          make -j$(nproc) && make test
+          make -j$(nproc) && make check
       - run: |
           lcov --directory . --capture --output-file coverage.info &&
           lcov -r coverage.info '*.l' '/usr/*' '*/tests/unit-tests/*' --output-file coverage.info &&
           lcov --list coverage.info"
           echo "Uploading CodeCov reports" && bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X xcode -F regresstests -s "$(pwd)" || echo \"CodeCov coverage report generation failed!\"
 
-  gcc7-release:
+  "gcc7-release":
     docker:
       - image: ceeac/boomerang-build-env:gcc7-release
     steps:
@@ -24,7 +38,7 @@ jobs:
           cmake -DCMAKE_BUILD_TYPE=Release -DBOOMERANG_BUILD_UNIT_TESTS=ON -DBOOMERANG_BUILD_REGRESSION_TESTS=OFF -DBOOMERANG_ENABLE_COVERAGE=OFF .. &&
           make -j$(nproc) && make test
 
-  clang6-debug:
+  "clang6-debug":
     docker:
       - image: ceeac/boomerang-build-env:clang6-debug
     steps:
@@ -34,7 +48,7 @@ jobs:
           cmake -DCMAKE_BUILD_TYPE=Debug   -DBOOMERANG_BUILD_UNIT_TESTS=ON -DBOOMERANG_BUILD_REGRESSION_TESTS=OFF -DBOOMERANG_ENABLE_COVERAGE=OFF .. &&
           make -j$(nproc) && make test
 
-  clang7-release:
+  "clang7-release":
     docker:
       - image: ceeac/boomerang-build-env:clang7-release
     steps:
@@ -44,11 +58,21 @@ jobs:
           cmake -DCMAKE_BUILD_TYPE=Release -DBOOMERANG_BUILD_UNIT_TESTS=ON -DBOOMERANG_BUILD_REGRESSION_TESTS=OFF -DBOOMERANG_ENABLE_COVERAGE=OFF .. &&
           make -j$(nproc) && make test
 
-
-  source-check:
+  "source-check":
     docker:
       - image: ceeac/boomerang-build-env:source-check
     steps:
       - checkout
       - run: |
           cd ~/project && ./scripts/run-clang-format.py -r src/ -e "*/machO/objc/*"
+
+workflows:
+  version: 2
+  build:
+    jobs:
+     - "gcc8-debug-cov"
+     - "gcc8-regress-cov"
+     - "gcc7-release"
+     - "clang6-debug"
+     - "clang7-release"
+     - "source-check"
